### ISSUE TITLE
option -f and --from-code= do not seem to work 

### ISSUE THREAD

**Issue by phourglass** [idigdoug/TextTools#2]
Hello idigdoug,

I have started using wargs for batch conversions on Windows 10 64 bits (along with voidtools everything to do list of files).
It works fine for me (thanks) except the encoding option (required for accentuated characters):
`>wargs -f utf8
wargs: error : Unrecognized short argument 'f' in '-f'
wargs: error : Invalid command-line. Use 'wargs --help' for more information.`
Same for --from-code.

As a workaround, I use `wconv -f utf8 | wargs ` which works fine.
No big deal but I thought I would let you know.

Thanks for your software
Philippe

**Comment by idigdoug** [comment]
Fixed with release v1.0.2.
